### ISSUE TITLE
timeout dla zeep

### ISSUE THREAD

**Issue by adi-** [rolzwy7/RegonAPI#3]
Domyślnie timeout dla zeep.Transport to 300 sekund! https://github.com/mvantellingen/python-zeep/blob/0d21568f91ea5e703a67e80c2bdf877768cc442b/src/zeep/transports.py#L23

Dobrze by było, gdyby `RegonAPI` miał możliwość nadpisywania tej wartości.

**Comment by adi-** [comment]
Każde jedno wyszukanie w RegonAPI, czyli request wykonywany przez `zeep.Transport` czekający przez 300 sekund na odpowiedź od serwera, blokuje wątek w serwerze aplikacji. Jeśli wątków nie jest za wiele, to wystarczy w 5 minut wykonać tylko pare zapytań, aby całkowicie zablokować serwer webowy.

**Comment by rolzwy7** [comment]
Cześć

Nie byłem tego świadomy 😅, dziękuję za zwrócenie na to uwagi.

===

 (v1.2.1) Added parameters 'timeout' and 'operation_timeout' in constructor of class 'RegonAPI', corresponding to parameters with same name of class 'Transport' from zeep library.

**Comment by adi-** [comment]
Extra! Zamykam.

**Comment by adi-** [comment]
Hej! Jest jeszcze "gdzieś" problem w przypadku błędu z połączeniem. Mam teraz problem z aplikacja, gdyż GUS w związku z dzisiejszą awaria wyciął zapytania z serwerów z IP poza Polską. Te timeouty które zostały dodane są niewystarczające.

**Comment by adi-** [comment]
Załączam stack:

```
Traceback (most recent call last):
 File "/opt/venvs/xxx/lib/python3.8/site-packages/urllib3/connection.py", line 159, in _new_conn
   conn = connection.create_connection(
 File "/opt/venvs/xxx/lib/python3.8/site-packages/urllib3/util/connection.py", line 84, in create_connection
   raise err
 File "/opt/venvs/xxx/lib/python3.8/site-packages/urllib3/util/connection.py", line 74, in create_connection
   sock.connect(sa)

During handling of the above exception ([Errno 110] Connection timed out), another exception occurred:
 File "/opt/venvs/xxx/lib/python3.8/site-packages/urllib3/connectionpool.py", line 670, in urlopen
   httplib_response = self._make_request(
 File "/opt/venvs/xxx/lib/python3.8/site-packages/urllib3/connectionpool.py", line 381, in _make_request
   self._validate_conn(conn)
 File "/opt/venvs/xxx/lib/python3.8/site-packages/urllib3/connectionpool.py", line 978, in _validate_conn
   conn.connect()
 File "/opt/venvs/xxx/lib/python3.8/site-packages/urllib3/connection.py", line 309, in connect
   conn = self._new_conn()
 File "/opt/venvs/xxx/lib/python3.8/site-packages/urllib3/connection.py", line 171, in _new_conn
   raise NewConnectionError(

During handling of the above exception (<urllib3.connection.HTTPSConnection object at 0x7f0524e57d00>: Failed to establish a new connection: [Errno 110] Connection timed out), another exception occurred:
 File "/opt/venvs/xxx/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
   resp = conn.urlopen(
 File "/opt/venvs/xxx/lib/python3.8/site-packages/urllib3/connectionpool.py", line 726, in urlopen
   retries = retries.increment(
 File "/opt/venvs/xxx/lib/python3.8/site-packages/urllib3/util/retry.py", line 446, in increment
   raise MaxRetryError(_pool, url, error or ResponseError(cause))

During handling of the above exception (HTTPSConnectionPool(host='[wyszukiwarkaregon.stat.gov.pl](http://wyszukiwarkaregon.stat.gov.pl/)', port=443): Max retries exceeded with url: /wsBIR/wsdl/UslugaBIRzewnPubl-ver11-prod.wsdl (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f0524e57d00>: Failed to establish a new connection: [Errno 110] Connection timed out'))), another exception occurred:
 File "/opt/venvs/xxx/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
   response = get_response(request)
 File "/opt/venvs/xxx/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
   response = wrapped_callback(request, *callback_args, **callback_kwargs)
 File "/opt/venvs/xxx/lib/python3.8/site-packages/django/views/generic/base.py", line 70, in view
   return self.dispatch(request, *args, **kwargs)
 File "/opt/venvs/xxx/lib/python3.8/site-packages/formtools/wizard/views.py", line 244, in dispatch
   response = super().dispatch(request, *args, **kwargs)
 File "/opt/venvs/xxx/lib/python3.8/site-packages/django/views/generic/base.py", line 98, in dispatch
   return handler(request, *args, **kwargs)
 File "/opt/venvs/xxx/lib/python3.8/site-packages/formtools/wizard/views.py", line 296, in post
   self.storage.set_step_data(self.steps.current, self.process_step(form))
 File "/opt/venvs/xxx/lib/python3.8/site-packages/xxx/service_requests/views.py", line 185, in process_step
   bir_data = get_bir_data(form.cleaned_data.get('company_nip'))
 File "/opt/venvs/xxx/lib/python3.8/site-packages/xxx/core/utils.py", line 104, in get_bir_data
   api = RegonAPI(bir_version="bir1.1", is_production=True, timeout=5, operation_timeout=5)
 File "/opt/venvs/xxx/lib/python3.8/site-packages/RegonAPI/regon_api.py", line 102, in __init__
   self.client = Client(wsdl=self.wsdl)
 File "/opt/venvs/xxx/lib/python3.8/site-packages/zeep/client.py", line 61, in __init__
   self.wsdl = Document(
 File "/opt/venvs/xxx/lib/python3.8/site-packages/zeep/wsdl/wsdl.py", line 82, in __init__
   document = self._get_xml_document(location)
 File "/opt/venvs/xxx/lib/python3.8/site-packages/zeep/wsdl/wsdl.py", line 142, in _get_xml_document
   return load_external(
 File "/opt/venvs/xxx/lib/python3.8/site-packages/zeep/loader.py", line 74, in load_external
   content = transport.load(url)
 File "/opt/venvs/xxx/lib/python3.8/site-packages/zeep/transports.py", line 110, in load
   content = self._load_remote_data(url)
 File "/opt/venvs/xxx/lib/python3.8/site-packages/zeep/transports.py", line 126, in _load_remote_data
   response = self.session.get(url, timeout=self.load_timeout)
 File "/opt/venvs/xxx/lib/python3.8/site-packages/requests/sessions.py", line 555, in get
   return self.request('GET', url, **kwargs)
 File "/opt/venvs/xxx/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
   resp = self.send(prep, **send_kwargs)
 File "/opt/venvs/xxx/lib/python3.8/site-packages/requests/sessions.py", line 655, in send
   r = adapter.send(request, **kwargs)
 File "/opt/venvs/xxx/lib/python3.8/site-packages/requests/adapters.py", line 516, in send
   raise ConnectionError(e, request=request)

Exception Type: ConnectionError at /pl/serwis/nowe-zlecenie-stacjonarne/
Exception Value: HTTPSConnectionPool(host='[wyszukiwarkaregon.stat.gov.pl](http://wyszukiwarkaregon.stat.gov.pl/)', port=443): Max retries exceeded with url: /wsBIR/wsdl/UslugaBIRzewnPubl-ver11-prod.wsdl (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f0524e57d00>: Failed to establish a new connection: [Errno 110] Connection timed out'))
```

**Comment by adi-** [comment]
Skrócony:

```
Traceback (most recent call last):
 File "/opt/venvs/xxx/lib/python3.8/site-packages/xxx/core/utils.py", line 105, in get_bir_data
   api = RegonAPI(bir_version="bir1.1", is_production=True, timeout=5, operation_timeout=5)
 File "/opt/venvs/xxx/lib/python3.8/site-packages/RegonAPI/regon_api.py", line 102, in __init__
   self.client = Client(wsdl=self.wsdl)
 File "/opt/venvs/xxx/lib/python3.8/site-packages/zeep/client.py", line 61, in __init__
   self.wsdl = Document(
 File "/opt/venvs/xxx/lib/python3.8/site-packages/zeep/wsdl/wsdl.py", line 82, in __init__
   document = self._get_xml_document(location)
 File "/opt/venvs/xxx/lib/python3.8/site-packages/zeep/wsdl/wsdl.py", line 142, in _get_xml_document
   return load_external(
 File "/opt/venvs/xxx/lib/python3.8/site-packages/zeep/loader.py", line 74, in load_external
   content = transport.load(url)
 File "/opt/venvs/xxx/lib/python3.8/site-packages/zeep/transports.py", line 110, in load
   content = self._load_remote_data(url)
 File "/opt/venvs/xxx/lib/python3.8/site-packages/zeep/transports.py", line 127, in _load_remote_data
   response.raise_for_status()
 File "/opt/venvs/xxx/lib/python3.8/site-packages/requests/models.py", line 943, in raise_for_status
   raise HTTPError(http_error_msg, response=self)

Exception Type: HTTPError
Exception Value: 503 Server Error: Service Unavailable for url: https://wyszukiwarkaregon.stat.gov.pl/wsBIR/wsdl/UslugaBIRzewnPubl-ver11-prod.wsdl
Request data not supplied
```
